### ISSUE TITLE
Browserify Issue

### ISSUE THREAD

**Issue by born2defy** [ethul/purescript-react-example#5]
Hi there - I think there is a minor issue with this repo.  The build script outputs the bundled js file to public/scripts/Main.js but there is no 'scripts' directory in the repo.  For me it caused the process to fail until I created the directory manually.

**Comment by ethul** [comment]
Good catch! We can add a .gitkeep in that directory. I might have time to
do this tonight, but a PR is welcome.

**Comment by ethul** [comment]
Closed by #6
